### PR TITLE
move inline Javasript to external

### LINKED ISSUE #15: Avoid using inline javascript
We should never use inline javascript, it's evil. Also, it doesn't work with strict content security policies.

### PR DESCRIPTION
**Pull request by melanger**
and separate data from code

fixes #15

### CODE REVIEW

File: www/assets/js/webauthn.js [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+function authButtonClick() {
+    navigator.credentials.get(publicKeyCredentialRequestOptions)
+    .then((cred) => {
+        console.log('NEW CREDENTIAL', cred);
+        document.getElementById('resp').value = cred.id;
+        var enc = new TextDecoder('utf-8');
+        document.getElementById('data_raw_b64').value = btoa(ArrayBufferToString(cred.response.clientDataJSON));
+        document.getElementById('data').value = enc.decode(cred.response.clientDataJSON);
+        document.getElementById('authdata').value = btoa(ArrayBufferToString(cred.response.authenticatorData));
+    document.getElementById('sigdata').value = btoa(ArrayBufferToString(cred.response.signature));
```
Comment (tvdijen) [inline www/assets/js/webauthn.js]: nitpick: indentation is off

File: templates/webauthn.twig [hunk 2]
```diff
@@ -24,21 +22,20 @@
...
-    {% if regForm|length > 0 %}
+    {% if regURL|length > 0 %}
         <form id='regform' method='POST' action='{{ regURL|raw }}'>
             <input type='hidden' id='resp' name='response_id' value='0'/>
             <input type='hidden' id='data' name='attestation_client_data_json' value='nix'/>
             <input type='hidden' id='attobj' name='attestation_object' value='mehrnix'/>
             <input type='hidden' id='type' name='type' value='something'/>
             <input type='hidden' id='operation' name='operation' value='REG'/>
-            <button type='button' onClick="{{ regForm|raw }}" onsubmit='false' >{{ '{webauthn:webauthn:newTokenButton}'|trans }}</button>
+            <button type='button' id='regformSubmit'>{{ '{webauthn:webauthn:newTokenButton}'|trans }}</button>
```
Comment (jaimeperez) [inline templates/webauthn.twig]: With the new user interface / templates, we're aiming at actual strings in the templates, so that it's easier to see them in context for the translators, and also we get the original text in english if there are no translations, rather than a weird tag that doesn't mean anything.

File: templates/webauthn.twig [hunk 3]
```diff
@@ -24,21 +22,20 @@
...
             {{ '{webauthn:webauthn:newTokenName}'|trans }} <input 
                 type='text' 
                 id='tokenname' 
                 name='tokenname' 
                 size='40' 
-                value='{{ '{webauthn:webauthn:newTokenDefaultName}'|trans }} {{ "now"|date('Y-m-d', timezone="Europe/Luxembourg") }}' onkeydown="if (event.keyCode == 13)
-                            return false;"/>
+                value='{{ '{webauthn:webauthn:newTokenDefaultName}'|trans }} {{ "now"|date('Y-m-d', timezone="Europe/Luxembourg") }}' />
```
Comment (jaimeperez) [inline templates/webauthn.twig]: Same here.

Also, I don't think we should be fixing the timezone here. I don't know why it's like that, but it definitely shouldn't be the case.

File: templates/webauthn.twig [hunk 4]
```diff
@@ -71,7 +68,8 @@
         {% else %}
             {{ '{webauthn:webauthn:wantsModification}'|trans }}
         {% endif %}</input><br/>
-        <button type='button' onClick="{{ authForm|raw }}" onsubmit='false' >{{ '{webauthn:webauthn:authTokenButton}'|trans }}</button>
+        <button type='button' id='authformSubmit'>{{ '{webauthn:webauthn:authTokenButton}'|trans }}</button>
```
Comment (jaimeperez) [inline templates/webauthn.twig]: Yet another translation that should be the original text.

File: templates/webauthn.twig (hunk 3 above)
Comment (restena-sw) [reply templates/webauthn.twig]: Sorry for the timezone, it's a leftover from my initial local deployment. This should of course be the globally configured timezone of simpleSAMLphp as per main config file.

File: www/assets/js/webauthn.js (hunk 1 above)
Comment (melanger) [reply www/assets/js/webauthn.js]: Indentation and spacing is incorrect in more places - I did not want to mix refactoring into this PR. I just moved the code from PHP and I would address format in another PR. Is that OK?

**Comment by melanger** [comment]
@jaimeperez Both translations and timezone can be addressed in a separate PR, I did not want to mix things together. I will also break my twig2php script, but I can probably work around that :)

**Comment by melanger** [comment]
Tweaks addressed in #20

**Comment by jaimeperez** [comment]
> @jaimeperez Both translations and timezone can be addressed in a separate PR, I did not want to mix things together. It will also break my twig2php script, but I can probably work around that :)

I'm fine with that approach! 👍
